### ISSUE TITLE
how do you execute? missing data?

### ISSUE THREAD

**Issue by j2l** [netgrif/petriflow.js#29]
Hello,
I'm using the mortgage example xml and your code example but I don't find how to call execute() on it.
Additionally, the resulting javascript  object is missing data in multiple sections:
`All:{"_model":{"_id":"mortgage","_version":"","_initials":"MTG","_title":{"_value":"Mortgage"},"_icon":"","_defaultRole":true,"_anonymousRole":false,"_transitionRole":false,"_caseName":{"_value":"","_dynamic":false},"_transitions":{},"_places":{},"_arcs":{},"_data":{},"_transactions":{},"_roles":{},"_functions":[],"_roleRefs":{},"_userRefs":{},"_i18ns":{},"_processEvents":{},"_caseEvents":{},"_mappings":{}},"_errors":[],"_warnings":[],"_info":["Tags <valid> of field loan_amount changed to validations","1 action of data variable loan_amount converted into event actions","Tags <valid> of field period changed to validations","1 action of data variable period converted into event actions","1 action of data variable calc converted into event actions","1 action of data variable postal converted into event actions","Values of field type changed to options","Values of field insurance changed to options","Tag <values>area</values> of field text_2 changed to component","Tag <values>area</values> of field text_3 changed to component"]}`

**Comment by mazarijuraj** [comment]
Hello,

thank you for your question. The main goal of petriflow.js is just to store the Petriflow model in JavaScript objects, so there is no execute function. We use petriflow.js to create and manipulate with the Petriflow model in our [Application Builder](https://builder.netgrif.com/modeler). To execute these models you can use the community version of [Application Engine](https://github.com/netgrif/application-engine), demo is also available at [demo.netgrif.com](https://demo.netgrif.com/login) after registration. Please visit our [website](https://netgrif.com/) and [Youtube channel](https://youtu.be/iU1QGPUnXUs) to learn more about Builder and Engine.

Could you please provide us with the xml file and the code that you use to import it?

**Comment by j2l** [comment]
Thank you @mazarijuraj 
The mortgage xml is from your website, see enclosed.
[mortgage_modeler.xml.zip](https://github.com/netgrif/petriflow.js/files/8008198/mortgage_modeler.xml.zip)
The code was just following your example, I didn't keep it sorry.

If you know some petri javascript library that executes please let me know :)
Thank you
